name: turing_google_map
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.2.3
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  dio: ^4.0.6
  intl: ^0.18.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
